name = "site"

account_id = "1f3c68e105e53717b922b03fbbc710ff"
workers_dev = true

compatibility_date = "2024-01-01"

[site]
bucket = "./.svelte-kit/cloudflare"
entry-point = "workers-site"

[env.production]
name = "site"
workers_dev = false
route = "https://alancria.xyz/*"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "./src"
output_path = "./.svelte-kit/cloudflare"
