name = "site"
workers_dev = true
compatibility_date = "2023-08-07"
main = ".svelte-kit/cloudflare/_worker.js"

[[durable_objects.bindings]]
name = "room"
class_name = "DurableObjectNameSpace"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectNameSpace"]